/*
Tätä tiedostoa käytetään PROKO-järjestelmän kielitiedostona.
Muutokset näkyvät heti järjestelmässä kunhan kehitystila on päällä (npm run dev). Kehitys -ja tuotantoympäristön käytön selitykset löytyvät dokumentaatiosta.
Kielitiedostossa on käännökset suomeksi ja englanniksi.
Käännökset ovat muokattavissa ilman sitä käyttävän koodin muokkaamista.
Käännöksillä on selittävät nimet mutta niiden käyttö järjestelmässä vaatii tarkkuutta sillä on vaikea tietää missä kaikkialla käännöksiä käytetään.
Huomioitavaa käytöstä:
    Kokonaan uusien käännösten lisääminen ei onnistu ilman käännöstä käyttävän koodin muokkaamista.
    Käännöksiä tulee aina olla 2kpl, suomeksi sekä englanniksi. 
    Käännöksiä ei ole suositeltavaa poistaa, sillä ne voivat olla käytössä jossain koodissa.
Suositeltavaa onkin tehdä vain pieniä muutoksia käännöksiin niin ohjelman logiikka säilyy ennallaan. Esimerkiksi yliopisto käännökseen voi tehdä muutoksen eri yliopiston nimeen. 
Tai esim. laskutusohjeita voi muuttaaa tiedostosta. 
*************************************************************************************************************************************

*************************************************************************************************************************************
*/

export const translator = (lang) => {
const english = {
        aiheitaKasitelty: "Subjects",
        AIHE: 'SUBJECT',
        aukaisekaikkioppilaat: 'Open all students',
        Aihe2: 'Subject',
        Aihe: 'Topic',
        ALAOTSIKKO: 'SUBTITLE',
        Asetukset: 'Settings',
        etunimisukunimi: 'Firstname Lastname',
        Ei: 'No',
        eipalautettu: 'Not returned',
        eionnistuttupoistamaan: 'could not be removed',
        etsinimellaOhje: 'Search student or tutor by name',
        haluatkovarmastipoistaa: 'Are you sure you want to remove',
        Huomenna: 'Tomorrow',
        hoursKesto: "Billed",
        hoursSisallytysKesto: "Included",
        Hyva: 'Good',
        ilmoitusPlaceholder: "The announcement written here is visible to other student tutors and supervisors.",
        IlmoitusNakyvyysOhje: 'Who do you want to see the announcement',
        Ilmoitukset: 'Announcements',
        Istunto: 'Session',
        istuntopaivitetty: 'Session renewed',
        jaTapa: 'and mode',
        Julkaise: 'Publish',
        jotainmenipieleen: 'Something went wrong',
        Kaikkipalautteet: 'All feedbacks',
        katsokorttia: 'Examine card',
        KirjauduUlos: 'Logout',
        kieliasetus: 'Change language',
        Kertyma: 'Accumulation',
        kertymaSisallytys: "Accumulation (included in work time)",
        kertymaLaskutus: "Accumulation (billed separately)",
        Kesto: 'Duration (to separately bill university for tutoring)',
        kestoOhjauskerrat: "Duration (to be billed)",
        KestoSisallytys: "Duration (to include bill in work time)",
        kestoSisallytysOhjauskerrat: "Duration (incl. in work time)",
        katsopalautusta: 'Examine returned card',
        kotitehtOhje: 'Possible homework before the next meeting time (for group or Student Tutor)',
        kirjauspohjaInfo: 'Here you can find all the necessary info for billing of tutoring.',
        kirjauspohjaOtsikko: 'Group guidance base record',
        klo: 'clock',
        kortti: 'card',
        Kortti: 'Card',
        korttiTiedot: 'Returned cards and discussed topics',
        Korttia: 'Card',
        Kortteja: 'Cards',
        Korttiin: 'To card',
        Kylla: 'Yes',
        laskutusInfo: "Use the box below only to report tutoring hours for inclusion in your university salary. (for university workers only)",
        LisaaIlmoitus: 'Add new announcement to the message board.',
        Liikkuen: 'Exercising',
        Linkkivoimassa: 'The link is valid for',
        lisaksikaydyt: 'Additional topics discussed',
        luotu: 'created',
        luouusikortti: 'Create new card',
        lukuina: 'as numbers',
        Lisaa: 'Add',
        Lasnaolo: 'presence',
        Lahettaja: 'Sender',
        Maara: 'Amount',
        mitamuokkasit: 'What did you change from the card?',
        minuuteissa: 'in MINUTES',
        Muokkaa: 'Edit',
        Muokkauksia: 'Edits',
        Muokkaukset: 'Edits',
        Muutoin: 'Other',
        Nimi: 'Name',
        Nakyvyys: 'Visibility',
        Ohjauskerrat: 'Guidances',
        Opiskelijat: 'Students',
        Opiskelija: 'Student',
        opiskelija: 'student',
        Opiskelijallaoltavanimi: 'Student must have a name',
        opiskelijaa: 'students',
        OHJAUSKERTA: "GUIDANCE SESSION",
        ohjauskesken: 'Guidance unfinished',
        ohjaussuoritettu: 'Guidance finished',
        Ohjauspaikka: 'Guidance location',
        Ohje: 'Instructions',
        Opiskellen: 'Studying',
        occOhje1: 'You must add guidance place and time',
        occOhje2: 'You have no students in your group',
        ohjaajannimi: 'Tutor name',
        omatmuistiinpanot: 'My notes',
        oulunyliopisto: 'Oulu university',
        Osallistunut: 'Participated',
        PDF: "Generate PDF",
        Pienryhmat: 'Groups',
        Pienryhma: 'Group',
        pienryhma: 'group',
        pienryhmaa: 'groups',
        pienryhmat: 'groups',
        piilotakaikkioppilaat: 'Hide all students',
        Palautukset: 'Returned',
        Palautteet: 'Feedbacks',
        Palautteita: 'Feedbacks',
        Peruuta: 'Cancel',
        Palautettu: 'Returned',
        Paikalla: 'present',
        Paikka: 'Place',
        Poissa: 'Absent',
        palautakortti: 'Fill the card',
        Palauta: 'Submit',
        Pelaten: 'Playing',
        Poista: 'Remove',
        poistettu: 'removed',
        pvmppkk: 'date (dd/mm)',
        paivamaaraJaTunnit: 'Dates and hours',
        palautePlaceholder: 'Your feedback will be used to make the cards even better.',
        paivitetty: 'updated',
        Ruokaillen: 'Eating',
        ryhmassasiOn: 'Your group has',
        salasananvaihtoviesti: 'Password changed successfully!',
        salasanaOhje: 'New password must be atleast 6 characters long. Max is 50 chars.',
        salasanaTasmays: 'New password must match in both fields',
        Sähkötekniikka: 'Electrical engineering',
        Tietosuojaseloste: 'Privacyinfo',
        Takaisin: 'Back',
        toteutusehdotus: 'Implementation proposal',
        tuovalmiskortti: 'Add a premade card',
        toiveetTarpeet: 'The wishes and information needs of the group for the next meetings are as follows',
        Tiedekunta: 'Faculty',
        Tila: 'State',
        tiedekuntaTietoSahko: 'Computer Science and Engineering',
        Tietotekniikka: 'Computer Science',
        Tietojenkäsittelytiede: 'Information technology',
        tunnit: 'hours',
        tutkintoOhjelma: 'Degree program',
        Tallenna: 'Save',
        talletettu: 'saved',
        Tanaan: 'Today',
        tahan: 'here',
        Tervetuloa: 'Welcome',
        Tekstipalautteet: 'Text feedbacks',
        uudista: 'renew ',
        Uusi: 'New',
        uusisalasana: 'New password',
        Vaatiikehittamista: 'Needs developing',
        valmiitakortteja: 'Premade cards',
        vaihdasalasana: 'Change password',
        vanhasalasana: 'Old password',
        Varit: 'Colors',
        variInfo: 'If you are having difficulties with green and red colors, you can change the colorscheme more suitable for you.',
        Viesti: 'Message',
        Voitpyytaa: 'You can ask for student feedback with the help of feedback link',
        Yhteensa: 'Total',
        Yht: 'Tot.',
        kayttajaaEiLoydy: 'user not found',
        OletusKortit: "Default Cards",
        Yhteenveto: "Overview",
        KorttienJakauma: "Cards-%",
        alkuperainenKortti: "original",
        muokattuKortti: "modified",
        omaKortti: "custom",
        OsallistumisJakauma: "Participation-%",
        paikalla: "present",
        eiPaikalla: "not present",
        PalauteJakauma: "Feedback-%",
        ok_palaute: "ok",
        hyva_palaute: "good",
        huono_palaute: "needs improvement",
        OpiskelijoidenOsallistuminen: "Student Participation",
        Palaute: "Feedback",
        SuorituksetJakauma: "Completion-%",
        suoritettu_alkuperainen: "completed (original)",
        suoritettu_muokattu: "completed (modified)",
        OhjauskerranKesto: "Guidance time",
        MuokkausInfoJakauma: "Modification info-%",
        ei_muokattu: "not modified",
        muokattu: "modified",
        SuoritusInfoJakauma: "Completion info-%",
        suoritettu_kaikki: "completed (modified and not modified)",
        ei_suoritettu: "not completed",
        ei_suoritettu_poistettu: "not completed (removed)",
        Tilastot: "Stats",
        Sisalto: "Contents",
        aikajanaInfo_alkuperainen: " original card",
        aikajanaInfo_muokattu:  " modified card",
        aikajanaInfo_oma: " custom card",
        CSE: "Computer Science and Engineering",
        BME: "Biomedical Engineering",
        SEIS: "Software Engineering and Information Systems",
        DICE: "Digitalisation, Computing and Electronics",
        BATT: "BA-CSE",
        BATOL: "BA-IPS",
        WCE: "Wireless Communications Engineering",
        Electronics: "Electronics",
        SAS: "SAS",
        KUMMI: "Int. tutor",
        kummi: "Int. tutor",
        PRO: "Tutor",
        pro: "Tutor",
        superpro: "Super tutor",
        dekaani: "Dean",
        Suunnitelmat: "Planning",
        KoulutuksetSuunnitelmat: "Trainings and Planning",
        SuunnitelmatOtsikko: "Base records for planning and attending tutor training sessions",
        MaksimiLaskutus: "Maximum duration to bill",
        Lasku: "Duration",
        KestoKoulutus: "Maximum tutor training sessions bill is 10 h",
        KestoSuunnittelu: "Maximum tutoring planning bill is 5 h",
        KoulutuksetJaSuunnittelut: "Trainings and plannings",
        SuunnitelmaPohjaInfo: "In this page you can fill the trainings and your own tutoring planning that you have conducted",
        Toteutunut: "Actualized",
        Tunnit: "Hours",
        yliopisto: "University of Oulu",
        ToteutuneetKoulutukset: "Actualized trainings: ",
        ToteutuneetSuunnitelmat: "Actualized plannnig: ",
        Submit: "Submit",
        Koulutukset: "Trainings",
        MaksimiKesto: "Max duration",
        ToteutunutKesto: "Actual duration",
    }

    const finnish = {
        aiheitaKasitelty: "Aiheita",
        AIHE: 'AIHE',
        aukaisekaikkioppilaat: 'Aukaise kaikki oppilaat',
        Aihe2: 'Aihe',
        Aihe: 'Aihe',
        ALAOTSIKKO: 'ALAOTSIKKO',
        Asetukset: 'Asetukset',
        etunimisukunimi: 'Etunimi Sukunimi',
        Ei: 'Ei',
        eipalautettu: 'Ei palautettu',
        eionnistuttupoistamaan: 'ei onnistuttu poistamaan',
        etsinimellaOhje: 'Etsi oppilas tai ohjaaja nimellä',
        haluatkovarmastipoistaa: 'Haluatko varmasti poistaa',
        Huomenna: 'Huomenna',
        hoursKesto: "Laskutetaan",
        hoursSisallytysKesto: "Sisällytetään",
        Hyva: 'Hyvä',
        ilmoitusPlaceholder: "Tähän kirjoitettu ilmoitus näkyy tiedekuntasi muille tuutoreille ja supertuutoreille",
        IlmoitusNakyvyysOhje: 'Kenen haluat näkevän ilmoituksen',
        Ilmoitukset: 'Ilmoitukset',
        Istunto: 'Istunto',
        istuntopaivitetty: 'Istunto päivitetty',
        jaTapa: 'ja tapa',
        jotainmenipieleen: 'Jotain meni pieleen',
        Julkaise: 'Julkaise',
        Kaikkipalautteet: 'Kaikki palautteet',
        kotitehtOhje: 'Mahdollinen kotitehtävä ensi kertaan mennessä (ryhmälle tai tuutorille)',
        kirjauspohjaInfo: 'Tästä kirjauspohjalta löydät tarvittavat tiedot tuutoroinnin laskutukseen.',
        kirjauspohjaOtsikko: 'Tuutoriohjausten, koulutusten, ja suunnitelmien yhteenveto',
        klo: 'klo',
        kortti: 'kortti',
        Kortti: 'Kortti',
        korttiTiedot: 'Palautetut kortit ja käydyt aiheet',
        Korttia: 'Korttia',
        Kortteja: 'Kortteja',
        Korttiin: 'Korttiin',
        katsokorttia: 'Katso ohjauskorttia',
        KirjauduUlos: 'Kirjaudu ulos',
        kieliasetus: 'Change language',
        Kertyma: 'Kertymä',
        kertymaSisallytys: "Kertymä (sisällytetään työaikaan)",
        kertymaLaskutus: "Kertymä (laskutetaan erillisesti)",
        Kesto: 'Laskutetaan yliopistolta',
        kestoOhjauskerrat: "Laskutetaan yliopistolta",
        KestoSisallytys: "Sisällytetään työaikaan",
        kestoSisallytysOhjauskerrat: "Sisällytetään työaikaan",
        katsopalautusta: 'Katso palautusta',
        Kylla: 'Kyllä',
        laskutusInfo: "Käytä alempaa kenttää vain sisällyttämään tuutorointitunnit kuukausipalkkaasi (yliopiston työntekijöille)",
        luotu: 'luotu',
        luouusikortti: 'Luo uusi ohjauskortti',
        LisaaIlmoitus: 'Lisää uusi ilmoitus ilmoitustaululle.',
        Liikkuen: 'Liikkuen',
        Linkkivoimassa: 'Linkki on voimassa',
        lisaksikaydyt: 'Lisäksi käydyt aiheet',
        Lisaa: 'Lisää',
        Lasnaolo: 'Läsnäolo',
        lukuina: 'lukuina',
        Lahettaja: 'Lähettäjä',
        Maara: 'Määrä',
        Muutoin: 'Muutoin',
        mitamuokkasit: 'Mitä muokkasit ohjauskortista?',
        minuuteissa: 'MINUUTEISSA',
        Muokkaa: 'Muokkaa',
        Muokkauksia: 'Muokkauksia',
        Muokkaukset: 'Muokkaukset',
        Nimi: 'Nimi',
        Nakyvyys: 'Näkyvyys',
        OHJAUSKERTA: "OHJAUSKERTA",
        Ohjauskerrat: 'Ohjauskerrat',
        ohjauskesken: 'Tuutorointi kesken',
        ohjaussuoritettu: 'Tuutorointi suoritettu',
        Ohje: 'Ohje',
        Opiskelijat: 'Opiskelijat',
        Opiskelija: 'Opiskelija',
        opiskelija: 'opiskelija',
        Opiskelijallaoltavanimi: 'Opiskelijalla pitää olla nimi',
        opiskelijaa: 'opiskelijaa',
        occOhje1: 'Ohjauspaikka, ja ohjausaika täytyy määrittää',
        occOhje2: 'Ryhmässäsi ei ole yhtään oppilasta',
        Ohjauspaikka: 'Ohjauspaikka',
        Opiskellen: 'Opiskellen',
        omatmuistiinpanot: 'Omat muistiinpanot',
        oulunyliopisto: 'Oulun yliopisto',
        ohjaajannimi: 'Tuutorin nimi',
        Osallistunut: 'Osallistunut',
        Paikka: 'Paikka',
        PDF: "Luo PDF",
        Pienryhmat: 'Ryhmät',
        Pienryhma: 'Ryhmä',
        pienryhma: 'ryhmä',
        pienryhmaa: 'Ryhmää',
        pienryhmat: 'Ryhmät',
        piilotakaikkioppilaat: 'Piilota kaikki oppilaat',
        Peruuta: 'Peruuta',
        Palautettu: 'Palautettu',
        Pelaten: 'Pelaten',
        paivamaaraJaTunnit: 'Päivämäärä ja ohjaustunnit',
        pvmppkk: 'pvm (pp/kk)',
        Poista: 'Poista',
        palautePlaceholder: 'Antamaasi palautetta käytetään ohjauskorttien kehittämisessä entistä paremmiksi.',
        Paikalla: 'Paikalla',
        Palautukset: 'Palautukset',
        Palautteet: 'Palautteet',
        Palautteita: 'Palautteita',
        Poissa: 'Poissa',
        poistettu: 'poistettu',
        palautakortti: 'Täytä kortti',
        Palauta: 'Palauta',
        paivitetty: 'päivitetty',
        ryhmassasiOn: 'Ryhmässäsi on',
        Ruokaillen: 'Ruokaillen',
        salasanaOhje: 'Uuden salasanan tulee olla väh. 6 merkkiä pitkä. Maksimi 50 merkkiä',
        salasanaTasmays: 'Uuden salasanan tulee täsmätä',
        salasananvaihtoviesti: 'Salasana vaihdettu onnistuneesti!',
        Sähkötekniikka: "Elektroniikka ja tietoliikennetekniikka",

        tahan: 'tähän',
        Tietosuojaseloste: 'Tietosuojaseloste',
        tuovalmiskortti: 'Tuo valmis ohjauskortti',
        Takaisin: 'Takaisin',
        toiveetTarpeet: 'Ryhmältä tulleet toiveet ja tietotarpeet seuraaville kerroille',
        Tiedekunta: 'Tiedekunta',
        Tila: 'Tila',
        tiedekuntaTietoSahko: 'Tieto- ja sähkötekniikan tiedekunta',
        Tietotekniikka: 'Tietotekniikka',
        Tietojenkäsittelytiede: 'Tietojenkäsittelytiede',
        tutkintoOhjelma: 'Tutkinto-ohjelma',
        tunnit: 'tunnit',
        Tallenna: 'Tallenna',
        talletettu: 'talletettu',
        Tanaan: 'Tänään',
        Tervetuloa: 'Tervetuloa',
        Tekstipalautteet: 'Tekstipalautteet',
        toteutusehdotus: 'Toteutusehdotus',
        uudista: 'uudista ',
        Uusi: 'Uusi',
        uusisalasana: 'Uusi salasana',
        valmiitakortteja: 'Valmiita ohjauskortteja',
        Vaatiikehittamista: 'Vaatii kehittämistä',
        Varit: 'Värit',
        variInfo: 'Jos sinulla on hankaluuksia erottaa punaisen ja vihreän sävyjä, voit tästä muuttaa värejä helpommin erottuviksi.',
        vaihdasalasana: 'Vaihda salasana',
        vanhasalasana: 'Vanha salasana',
        Viesti: 'Viesti',
        Voitpyytaa: 'Voit pyytää oppilailta palautetta palautelinkin avulla',
        Yht: 'Yht.',
        Yhteensa: 'Yhteensä',
        kayttajaaEiLoydy: 'käyttäjää ei löydy',
        OletusKortit: "Kortit",
        Yhteenveto: "Yhteenveto",
        KorttienJakauma: "Kortit-%",
        alkuperainenKortti: "alkuperainen",
        muokattuKortti: "muokattu",
        omaKortti: "omatekemä",
        OsallistumisJakauma: "Osallistumis-%",
        paikalla: "paikalla",
        eiPaikalla: "ei paikalla",
        PalauteJakauma: "Palaute-%",
        ok_palaute: "ok",
        hyva_palaute: "hyvä",
        Tunnit: "Tunnit",

        huono_palaute: "vaatii kehittämistä",
        OpiskelijoidenOsallistuminen: "Opiskelijoiden Osallistuminen",
        Palaute: "Palaute",
        SuorituksetJakauma: "Suoritukset-%",
        suoritettu_alkuperainen: "suoritettu (alkuperäinen)",
        suoritettu_muokattu: "suoritettu (muokattu)",
        OhjauskerranKesto: "Ohjauksen kesto",
        MuokkausInfoJakauma: "Muokkaus info-%",
        ei_muokattu: "ei muokattu",
        muokattu: "muokattu",
        SuoritusInfoJakauma: "Suoritus info-%",
        suoritettu_kaikki: "suoritettu (muokatut ja ei muokatut)",
        ei_suoritettu: "ei suoritettu",
        ei_suoritettu_poistettu: "ei suoritettu (poistettu)",
        Tilastot: "Tilastot",
        Sisalto: "Sisältö",
        aikajanaInfo_alkuperainen: " alkuperäinen kortti",
        aikajanaInfo_muokattu:  " muokattu kortti",
        aikajanaInfo_oma: " omatekoinen kortti",
        CSE: "Computer Science and Engineering",
        BME: "Biomedical Engineering",
        SEIS: "Software Engineering and Information Systems",
        DICE: "Digitalisation, Computing and Electronics",
        BATT: "BA-CSE",
        BATOL: "BA-IPS",
        WCE: "Wireless Communications Engineering",
        Electronics: "Electronics",
        SAS: "SAS",
        KUMMI: "Int. tutor",
        kummi: "Int. tutor",
        PRO: "Tuutori",
        pro: "Tuutori", 
        superpro: "Supertuutori",
        dekaani: "Dekaani",
        Suunnitelmat: "Suunnitelmat",
        SuunnitelmatOtsikko: "Kirjauspohja: omat suunnitelmat ja tuutorikoulutukset",
        Lasku: "Kesto",
        MaksimiLaskutus: "Maksimi kesto",
        KestoKoulutus: "Maksimi koulutusten tuntisumma 10 h",
        KestoSuunnittelu: "Maksimi omien suunnitelmien tuntisumma 5 h",
        KoulutuksetJaSuunnittelut: "Koulutukset ja suunnittelu",
        SuunnitelmaPohjaInfo: "Tähän kirjauspohjaan voit täyttää käymäsi koulutukset ja omat tuutorointiin liittyvät suunnitelmasi",
        Toteutunut: "Toteutunut",
        yliopisto: "Oulun yliopisto",
        ToteutuneetKoulutukset: "Toteutuneet koulutukset: ",
        ToteutuneetSuunnitelmat: "Toteutuneet suunnitelmat: ",
        Submit: "Lähetä",
        KoulutuksetSuunnitelmat: "Koulutukset ja Suunnitelmat",
        Koulutukset: "Koulutukset",
        MaksimiKesto: "Koulutuksen maksimikesto",
        ToteutunutKesto: "Toteutunut kesto" 
    }

    if (lang === 'en') {
        return english
    }
    return finnish
}

